vich_uploader:
    db_driver: orm

    mappings:
       post_media:
           uri_prefix: /images/post_media
           upload_destination: '%kernel.project_dir%/public/images/post_media'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_remove: true  # determine whether to delete file upon removal of entity
           delete_on_update: true  # determine wheter to delete the file upon update of entity
       user_media:
           uri_prefix: /images/user_media
           upload_destination: '%kernel.project_dir%/public/images/user_media'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_remove: true  # determine whether to delete file upon removal of entity
           delete_on_update: true  # determine wheter to delete the file upon update of entity

